name: bep
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.3
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.2.1
  dio: ^5.0.1
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.10
  fluttertoast: ^8.2.1

  # firebase_auth: ^3.1.1

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/map_style.json
    - assets/
    - assets/images/
    - assets/images/icon.png
    - assets/images/google-logo.png
    - assets/images/paypal-donate-button.png
