// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMA8FLpk_Q3MUhDnh75yrCMuiJmb7Xj-0',
    appId: '1:702153606455:web:6b3593b82105df413206b2',
    messagingSenderId: '702153606455',
    projectId: 'gdsc-377005',
    authDomain: 'gdsc-377005.firebaseapp.com',
    databaseURL: 'https://gdsc-377005-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gdsc-377005.appspot.com',
    measurementId: 'G-E5HKVLW6TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB3NVTpmoaWi9xTB7H4ADFSxScmsqC58w',
    appId: '1:702153606455:android:438e6689450481f13206b2',
    messagingSenderId: '702153606455',
    projectId: 'gdsc-377005',
    databaseURL: 'https://gdsc-377005-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gdsc-377005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwSrnUqpp5ALIESj1uTj9JB2PJigFKR1I',
    appId: '1:702153606455:ios:44e65440fe59e61f3206b2',
    messagingSenderId: '702153606455',
    projectId: 'gdsc-377005',
    databaseURL: 'https://gdsc-377005-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gdsc-377005.appspot.com',
    androidClientId: '702153606455-8ac2ocs7hlks0fj6u5ep5559rp9no9ri.apps.googleusercontent.com',
    iosClientId: '702153606455-37a0ra5htanbvsip59h8hn03ck4a21ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.bep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwSrnUqpp5ALIESj1uTj9JB2PJigFKR1I',
    appId: '1:702153606455:ios:44e65440fe59e61f3206b2',
    messagingSenderId: '702153606455',
    projectId: 'gdsc-377005',
    databaseURL: 'https://gdsc-377005-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gdsc-377005.appspot.com',
    androidClientId: '702153606455-8ac2ocs7hlks0fj6u5ep5559rp9no9ri.apps.googleusercontent.com',
    iosClientId: '702153606455-37a0ra5htanbvsip59h8hn03ck4a21ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.bep',
  );
}
